Repository guilhermeicarofr/Linkr-BackEnd, pull requests merged in 2022-10, with the labels that each got.

#3 Login route configured
  src/controllers/auth.controllers.js
  src/index.js
  src/middlewares/validate.auth.js
  src/routes/auth.routes.js
  src/schemas/auth.schema.js
Labels: enhancement

#14 Listing users that likes a post
  src/controllers/post.controller.js
  src/repositories/hashtags.repositories.js
  src/repositories/post.repository.js
  src/routes/post.routes.js
Labels: enhancement

#18 Insert or delete a like.
  src/controllers/post.controller.js
  src/middlewares/validate.post.js
  src/middlewares/validate.token.js
  src/repositories/post.repository.js
  src/routes/post.routes.js
Labels: enhancement

#21 Feat/delete post
  src/controllers/post.controller.js
  src/middlewares/validate.post.js
  src/repositories/post.repository.js
  src/routes/post.routes.js
Labels: enhancement

#22 List users by name
  src/controllers/user.controllers.js
  src/repositories/user.repositories.js
  src/routes/user.routes.js
Labels: enhancement

#23 List posts by hashtag name
  src/controllers/hashtags.controllers.js
  src/repositories/hashtags.repositories.js
  src/routes/hashtags.routes.js
Labels: enhancement

#28 User timeline
  src/repositories/user.repositories.js
Labels: bug

#35 Feat/share posts
  src/controllers/share.controllers.js
  src/index.js
  src/repositories/post.repositories.js
  src/repositories/share.repositories.js
  src/repositories/user.repositories.js
  src/routes/share.routes.js
Labels: enhancement

#37 Search users
  src/controllers/user.controllers.js
  src/repositories/comment.repositories.js
  src/repositories/user.repositories.js
Labels: fix

#39 Search users
  src/controllers/user.controllers.js
Labels: fix
